language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
  - curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o php-cs-fixer.phar
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - mkdir -p travis
  - cp ~/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - rm ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini

after_script:
  - curl -s https://gist.github.com/satooshi/4750401/raw > travis/ColorCLI.php
  - curl -s https://gist.github.com/satooshi/4752226/raw > travis/junit.php
  - curl -s https://gist.github.com/satooshi/4958593/raw > travis/pmd.php
  - curl -s https://gist.github.com/satooshi/4958909/raw > travis/checkstyle.php
  - php travis/checkstyle.php
  - php travis/pmd.php
  - php travis/junit.php
  - php composer/bin/coveralls -v --exclude-no-stmt