language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction

script: vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php composer/bin/coveralls -v