language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - cp ~/xdebug.ini ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - rm ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini

after_script:
  - php composer/bin/coveralls -v --exclude-no-stmt